// Code generated by go tool dist; DO NOT EDIT.
// This is a bootstrap copy of /Users/fpf/Downloads/go1.11.1/src/cmd/cgo/zdefaultcc.go

//line /Users/fpf/Downloads/go1.11.1/src/cmd/cgo/zdefaultcc.go:1
// Code generated by go tool dist; DO NOT EDIT.

package main

const defaultPkgConfig = `pkg-config`
func defaultCC(goos, goarch string) string {
	switch goos+`/`+goarch {
	}
	return "clang"
}
func defaultCXX(goos, goarch string) string {
	switch goos+`/`+goarch {
	}
	return "clang++"
}
