// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package impl

// Injectors from wire.go:

func Init() *App {
	foo := NewFoo()
	app := &App{
		Foo: foo,
	}
	return app
}
